### ISSUE TITLE
Naabu also supports IP Address Vector

### ISSUE THREAD

**Issue by c3l3si4n** [sidxparab/Subdomain-Enumeration-Guide#55]
Hey!

In the web-probing section, there's a mention that unimap is better than naabu due to it resolving domains and scanning only the unique IPs, but doesn't naabu also do that? It could be a recent feature but i think it might be worth to add something mentioning this. Specially considering that naabu has an easier syntax. 

```
What's so special about Unimap?

    You would be wondering why didn't we use Nmap/Naabu for port scanning purposes right?
    The answer lies in the way Unimap performs open port scanning.
    Sometimes many subdomains point to the same IP address. Hence, scanning the same IP again & again would lead us to an IP ban or greater execution time.
    Unimap uses its own technology to initially resolve the IP addresses of all subdomains, once this process is finished, it creates a vector with the unique IP addresses and launches a parallel scan with Nmap.

```

**Comment by sidxparab** [comment]
Hey @c3l3si4n ,
Yes, you are right. But when I documented the Naabu didn't have this feature.
Anyways, I am going to revamp the Gitbook in the next month. I would make the changes during that time.

Thanks!
